apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-metrics
  labels:
    app: db-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-metrics
  template:
    metadata:
      labels:
        app: db-metrics
    spec:
      containers:
        - name: metrics
          image: guangbo/db-metrics:dev
          env:
            - name: INFLUXDB_SERVER
              value: ""
            - name: INFLUXDB_PORT
              value: ""
            - name: MQTT_SERVER
              value: ""
            - name: MQTT_TOPIC
              value: ""
            - name: INFLUXDB_USERNAME
              value: ""
            - name: INFLUXDB_PASSWORD
              value: ""
            - name: DATABASE
              value: ""
